### ISSUE TITLE
DX containers class has IContentish through DexterityContent

### ISSUE THREAD

**Issue by jaroel** [plone/plone.dexterity#75]
The plone.dexterity.content.Container class gains the IContentish interface from Products.CMFCore.PortalContent.PortalContent via the DexterityContent class.

```python
class Container(
        PasteBehaviourMixin, DAVCollectionMixin, BrowserDefaultMixin,
        CMFCatalogAware, CMFOrderedBTreeFolderBase, DexterityContent):
```

```python
class DexterityContent(DAVResourceMixin, PortalContent, PropertyManager,
                       Contained):
```

This *will* trigger a bunch of event handlers normally registered for content objects only for folderish (container) objects too.

**Comment by davisagli** [comment]
IContentish is meant to be for all Dexterity content items, whether they are folderish or not. It sounds like you think it is meant to be only for non-folderish items, which is not correct. So it sounds like maybe the problem is that someone registered event handlers for IContentish thinking that they will not apply for folderish items? Which event handlers are you talking about and what problem are you having with them?

**Comment by rafaelbco** [comment]
I think this can be closed. My understanding always was that `IContentish` applies for all content items, folderish or not.

**Comment by jaroel** [comment]
yeah
