### ISSUE TITLE
Minor (or not so) optimization

### ISSUE THREAD

**Issue by gforcada** [plone/plone.dexterity#98]
On our website, www.freitag.de, we noticed that we spend lots of times (reported by Products.LongRequestLogger) on waiting for a lock in `__getattr__` method: https://github.com/plone/plone.dexterity/blob/master/plone/dexterity/content.py#L341

Just above that call to `SCHEMA_CACHE.get(self.portal_type)` there is already a small optimization: all dunder methods as well as a volatile property are ignored right away.

When looking specifically which names got there, we found out that there are 3 other common names that could benefit from that optimization (and given our numbers those three names account for almost 50% of the requests to get an attribute).

The names are:
- `im_self`: only for python 2 (on python 3 that was renamed to `__self__` and as a dunder it gets automatically ignored by the current optimizations
- `aq_inner`: Acquisition related, and thus not expected to be found within a dexterity object (right? :thinking: )
- `_Access_contents_information_Permission`: seems to come from `AccessControl` and again, just like `aq_inner` it most probably will be never ever be found within a dexterity object

I have a patch already, but creating the issue is also helpful to:
- describe the changes in more detail
- get the chance to others to provide their feedback :+1: 

Does the change sound reasonable? I was mentioning that the problem we had is on the locking, but if we can avoid hitting the lock because we bail out early that also gives us more chances to not have to get the lock to begin with :smile:

**Comment by datakurre** [comment]
@gforcada You must have seen this https://github.com/plone/plone.dexterity/tree/datakurre-no-getattr and maybe remember the related benchmark discussion at Community.

Worse is that the performance is greater the deeper the folder hierarchy is because anything requiring acquisition stops at every level at getattr. My opinion is that we did not notice severity of this in time on Plone 4, because the base folder was still Archetypes by then.

And if you go far enough back in time to see why Dexterity got that expensive “figure out default values for unset fields from the schema”-convenience, it looks almost an accident.

We have been running DX without the expensive getattr for two years for now and only problems have been some default behaviors that rely on that. (Sure we need to write our own code to coup with it.)

**Comment by gforcada** [comment]
@datakurre no, I was not aware of that branch :sweat_smile: and I barely remember the discussion at community.

We will first try my approach :tm:  :rofl: and if we are not happy with it, we will give it a spin to your solution as well.

As my patch is far less invasive as your branch, I *guess* it is safe to be merged and they could even be combined.

What's the reason you never ended up proposing a pull request with those changes? :thinking: I guess these default behaviors... but could they be patched up and make the code upstream?

If there are plans to make a major Plone release, maybe that's a good time to propose this breaking change as well :+1: that and @mauritsvanrees explicit acquisition could be quite a nice performance boost (if we can overcome the drawbacks, if there is any on them).

**Comment by datakurre** [comment]
Yes, your proposal sounds safe to merge :)

By the time when I forked there was also other issue cause by this same “feature” where z3c.forms ever saved values that matched the schema defaults, but David managed to fix that. And it seemed that the general mood was that “just avoiding acquisition in page templates” is better than dropping the magical attribute lookup :)
